---
:raw_data:
  :item_instance_reference: 1000909342
  :actor_instance_reference: 0
  :inventory_instance_reference: 0
  :global_file_reference: config/globals.yml
  :skill_point_reference: 0
  :max_economy_reference: 12000
